# Generated by Django 6.0.3 on 2026-04-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('screening', 'Screening'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('saved', 'Saved')], default='applied', max_length=20),
        ),
    ]
