# Generated by Django 6.0.3 on 2026-04-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_jobapplication_created_at_jobapplication_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
