# Generated by Django 6.0.3 on 2026-04-22 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_jobapplication_application_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={},
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='task',
            new_name='title',
        ),
        migrations.AddField(
            model_name='reminder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='priority',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
